const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");
const assert = require("node:assert/strict");

const previewPath = path.join(
  __dirname,
  "..",
  "ui-preview",
  "xbot-eagle-interaction-system-v5.html"
);

test("v5 pairing cards own type, asset, and status actions without a side inspector", () => {
  const html = fs.readFileSync(previewPath, "utf8");
  const pairScreen = html.slice(
    html.indexOf('<section id="screen-pair"'),
    html.indexOf('<section id="screen-manage"')
  );
  const aepScreen = html.slice(
    html.indexOf('<section id="screen-aep"'),
    html.indexOf('<section id="screen-pair"')
  );
  const script = html.match(/<script>([\s\S]*?)<\/script>/)?.[1] || "";
  assert.doesNotThrow(() => new Function(script));

  assert.match(html, /<select class="type-chip card-type-select/);
  assert.match(script, /className=`package-type-picker/);
  assert.match(script, /class="package-type-option/);
  assert.match(html, /data-card-type="\$\{p\.id\}"/);
  assert.match(html, /aria-label="选择包装类型：\$\{p\.name\}"/);
  assert.match(html, /\$\$\('\[data-card-type\]'\)/);
  assert.match(html, /data-card-asset="preview"/);
  assert.match(html, /data-card-asset="source"/);
  assert.match(html, /data-card-status="\$\{p\.id\}"/);
  assert.match(html, /class="card-name-input" data-card-name="\$\{p\.id\}"/);
  assert.match(html, /包装名称已更新/);
  assert.match(html, /\.pair-row:focus-within\{z-index:1;border-color:var\(--blue\);box-shadow:var\(--shadow-soft\)\}/);
  assert.match(html, /\.pair-row\.needs-action\{order:-1\}/);
  assert.doesNotMatch(html, /\.pair-row:hover\{[^}]*transform:/);
  assert.match(html, /\.row-select\{top:auto;right:10px;bottom:10px;left:auto;width:24px;height:24px/);
  assert.match(html, /\.pair-row :is\(button,input,select\):focus-visible\{outline:0;box-shadow:none\}/);
  assert.match(html, /id="pairProjectName" value="支付宝阿宝"/);
  assert.match(html, /id="successProject"/);
  assert.doesNotMatch(html, /class="brand"/);
  assert.doesNotMatch(html, /class="page-head"/);
  assert.match(html, /id="homeDropZone"/);
  assert.match(html, /class="hero-upload-icon"/);
  assert.match(html, /\.hero-upload-icon\{[^}]*box-shadow:none/);
  assert.match(html, /data-home-pick="aep">从AEP开始<\/button>/);
  assert.match(html, /data-home-pick="folder">从文件夹开始<\/button>/);
  assert.match(html, /id="homeAepPicker" type="file" accept="\.aep/);
  assert.match(html, /id="homeFolderPicker" type="file" webkitdirectory directory/);
  assert.match(script, /function routeHomeFiles\(files,source='auto'\)/);
  assert.match(script, /function bindHomeDropZone\(\)/);
  assert.match(script, /zone\.addEventListener\('drop'/);
  assert.match(script, /source!=='folder'&&names\.length===1/);
  assert.match(html, /id="pairAepBtn"[^>]*data-action="start-from-aep">从AEP开始<\/button>/);
  assert.match(html, /id="replaceFolderBtn"[^>]*data-action="replace-folder">更换文件夹<\/button>/);
  assert.match(script, /if\(act==='choose-aep'\|\|act==='start-from-aep'\)openSourcePicker\('#homeAepPicker'\)/);
  assert.match(script, /if\(act==='open-folder'\|\|act==='replace-folder'\)openSourcePicker\('#homeFolderPicker'\)/);
  assert.match(html, /id="crumbText"/);
  assert.match(html, /\.crumb strong\{color:var\(--ink\);font-size:16px/);
  assert.match(html, /manage-toolbar-actions/);
  assert.match(html, /class="aep-top-row"/);
  assert.match(html, /\.aep-top-row\{display:grid;grid-template-columns:minmax\(0,1\.35fr\) minmax\(300px,\.85fr\)/);
  assert.doesNotMatch(html, /class="aep-options-heading"/);
  assert.doesNotMatch(html, /<details class="panel aep-options">/);
  assert.match(html, /id="aepOutputPath"/);
  assert.match(html, /data-action="choose-output-path"/);
  assert.match(html, /id="aepOutputPathPicker" type="file" webkitdirectory/);
  assert.doesNotMatch(html, /<label>收集策略<\/label>/);
  assert.match(script, /输出路径已更新/);
  assert.match(html, /\.aep-layout\{grid-template-columns:218px minmax\(0,1fr\) 330px\;gap:14px;height:clamp\(460px,calc\(100vh - 294px\),680px\)/);
  assert.match(html, /\.manage-layout\{grid-template-columns:218px minmax\(0,1fr\) 330px\;gap:14px;height:clamp\(460px,calc\(100vh - 294px\),680px\)/);
  assert.match(html, /@media \(min-width:1181px\)\{#screen-manage \.manage-layout\{height:calc\(100vh - 150px\);min-height:460px\}\}/);
  assert.match(html, /\.manage-layout>\.manage-side,\.manage-layout>\.manage-main,\.manage-layout>\.manage-inspector\{min-height:0/);
  assert.match(html, /\.manage-layout>\.manage-side\{position:sticky;top:76px;z-index:3;align-self:start;height:max-content/);
  assert.match(html, /\.manage-layout>\.manage-inspector\{position:sticky;top:76px;z-index:3;align-self:start;height:max-content/);
  assert.match(html, /\.manage-layout>\.manage-main\{height:100%;overflow:auto/);
  assert.match(html, /\*\{scrollbar-width:thin;scrollbar-color:transparent transparent\}/);
  assert.match(html, /\*::-webkit-scrollbar\{width:4px;height:4px\}/);
  assert.match(html, /\*:hover::-webkit-scrollbar-thumb\{background:color-mix/);
  assert.match(script, /const renderManageInspectorNoHistory=renderManageInspector/);
  assert.match(script, /\$\('#manageInspector \.manage-history'\)\?\.remove\(\)/);
  assert.match(html, /\.aep-layout>\.aep-filter\{position:sticky;top:76px/);
  assert.match(html, /\.aep-layout>\.tree\{height:calc\(100% \+ 54px\);overflow:auto;overscroll-behavior:contain/);
  assert.match(html, /\.aep-layout>\.inspector\{position:sticky;top:76px/);
  assert.match(html, /\.aep-layout>\.aep-filter,\.aep-layout>\.tree,\.aep-layout>\.inspector\{height:100%;min-height:0/);
  assert.doesNotMatch(aepScreen, /class="bottom-bar"/);
  assert.doesNotMatch(pairScreen, /class="bottom-bar"/);
  assert.match(aepScreen, /data-bottom-sheet="aep"/);
  assert.match(pairScreen, /data-bottom-sheet="pair"/);
  assert.match(html, /#screen-pair \.pair-summary,#pairBottomSheetContent>\.bottom-sheet-section-head\{display:none\}/);
  assert.match(html, /id="bottomSheetBackdrop"/);
  assert.match(html, /\.bottom-sheet\{--bottom-sheet-peek:62px;position:fixed/);
  assert.match(html, /transform:translateY\(calc\(100% - var\(--bottom-sheet-peek\)\)\)/);
  assert.match(html, /\.bottom-sheet\.is-open\{transform:translateY\(0\)\}/);
  assert.match(html, /\.bottom-sheet-summary:active\{transform:none\}/);
  assert.match(html, /\.bottom-sheet-peek:hover\{background:var\(--panel-2\)\}/);
  assert.match(html, /\.bottom-sheet-summary:hover\{background:transparent\}/);
  assert.match(html, /\.bottom-sheet-peek::before\{display:none\}/);
  assert.match(html, /\.bottom-sheet-grabber-svg polyline\{fill:none;stroke:var\(--line-2\);stroke-width:1\.5;stroke-linecap:round;stroke-linejoin:round/);
  assert.match(html, /grabber-collapsed','2,4 9,4 16,4/);
  assert.match(html, /grabber-expanded','2,2 9,6 16,2/);
  assert.match(script, /function installBottomSheetGrabbers\(\)/);
  assert.match(script, /installBottomSheetGrabbers\(\)/);
  assert.match(html, /\.bottom-sheet-peek \.bottom-sheet-grabber\{display:none\}/);
  assert.match(html, /class="bottom-sheet-quick-actions"/);
  assert.doesNotMatch(html, /class="bottom-sheet-peek-action"/);
  assert.doesNotMatch(html, /class="bottom-sheet-footer"/);
  assert.match(html, /\.collection-rule\{display:inline-flex;align-items:center;justify-content:center;min-width:86px/);
  assert.doesNotMatch(html, /\.collection-rule\[aria-pressed="true"\]::before/);
  assert.match(html, /\.collection-rule:focus-visible\{border-color:var\(--blue\)/);
  assert.match(html, /\.bottom-sheet\{--bottom-sheet-peek:108px;left:10px/);
  assert.match(html, /\.toast\{top:76px;right:24px;bottom:auto;transform:translateY\(-8px\)\}/);
  assert.match(html, /@media \(max-width:840px\)\{\.toast\{top:72px;right:12px;max-width:calc\(100vw - 24px\)\}\}/);
  assert.match(html, /id="aepCollectionList"/);
  assert.match(script, /id:17,kind:'pre',name:'二维码-右下'/);
  assert.match(script, /17 个合成 · 16 个推荐交付 · 预览数据/);
  assert.doesNotMatch(aepScreen, /逐项收集规则<\/strong>/);
  assert.doesNotMatch(aepScreen, /每个合成可单独决定是否生成图片或收集工程文件/);
  assert.match(html, /#aepBottomSheetContent>\.bottom-sheet-list\{padding-top:14px\}/);
  assert.match(html, /id="pairSelectionList"/);
  assert.match(script, /collectImage:true,collectFile:true/);
  assert.match(script, /data-collect-output="image"/);
  assert.match(script, /data-collect-output="file"/);
  assert.match(script, /function collectionOutputLabel\(c\)/);
  assert.match(script, /x\.selected&&\(x\.collectImage\|\|x\.collectFile\)/);
  assert.match(script, /function renderPairSelectionSheet\(\)/);
  assert.match(script, /function toggleBottomSheet\(name\)/);
  assert.match(script, /收起逐项收集规则/);
  assert.match(script, /function trapBottomSheetFocus\(event\)/);
  assert.match(script, /else if\(activeBottomSheet\)\{closeBottomSheet\(\)/);
  assert.doesNotMatch(html, /<div class="head-actions"><button class="ghost-btn" data-action="open-aep">添加新包装<\/button>/);
  assert.match(script, /projectName='支付宝阿宝'/);
  assert.match(script, /function commitProjectName\(\)/);
  assert.match(script, /function syncPairProjectLabels\(visible\)/);
  assert.match(script, /项目名称不能为空/);
  assert.match(script, /将同步到命名与入库记录/);
  assert.match(script, /\$\('#pairProjectName'\)\.addEventListener\('change',commitProjectName\)/);
  assert.match(script, /if\(next==='success'\)\{/);
  assert.match(script, /\$\('#successProject'\)\.textContent=result\?\.project\|\|projectName/);
  assert.match(html, /function openPairStatusDrawer\(p\)/);
  assert.match(html, /openReplaceDrawer\(x\.dataset\.pair,x\.dataset\.cardAsset\)/);
  assert.match(html, /data-candidate-preview="\$\{f\}"/);
  assert.match(html, /openPreview\(\{name:b\.dataset\.candidatePreview,tone:b\.dataset\.candidateTone\|\|''\},'替换候选 · PNG'\)/);
  assert.match(html, /class="candidate-choice" data-candidate="\$\{f\}"/);
  assert.match(html, /currentIndex=Math\.max\(0,files\.indexOf\(current\)\)/);
  assert.match(html, /aria-pressed="\$\{selected\}"/);
  assert.match(html, /p\.preview=candidate\.dataset\.candidate/);
  assert.match(html, /p\.source=candidate\.dataset\.candidate/);
  assert.match(html, /role="status" aria-live="polite"/);
  assert.match(html, /role="dialog" aria-modal="true"/);
  assert.match(html, /event\.key==='Escape'/);
  assert.match(html, /function trapModalFocus\(event\)/);
  assert.match(html, /grid-template-columns:repeat\(auto-fill,minmax\(260px,1fr\)\)/);
  assert.doesNotMatch(pairScreen, /class="stepper"/);
  assert.doesNotMatch(aepScreen, /class="stepper"/);
  assert.doesNotMatch(pairScreen, /id="pairInspector"/);
  assert.doesNotMatch(html, /配对检查器/);
  assert.doesNotMatch(html, /<span class="tiny-pill">\$\{p\.type\?\('自动匹配/);
  assert.doesNotThrow(() => new Function(script));
});

test("v5 preview exposes the plugin update entry and demo update flow", () => {
  const html = fs.readFileSync(previewPath, "utf8");
  const script = html.match(/<script>([\s\S]*?)<\/script>/)?.[1] || "";

  assert.doesNotMatch(html, /id="updateEntry"/);
  assert.match(html, /id="tweakBtn"[^>]*data-update-available="true"/);
  assert.match(html, /class="settings-update"[^>]*data-action="open-updates"/);
  assert.match(html, /id="homeBtn"[^>]*aria-label="返回首页"[^>]*hidden><svg/);
  assert.doesNotMatch(html, /id="darkToggle"|id="compactToggle"/);
  assert.match(html, /id="motionToggle"/);
  assert.match(html, /id="screen-updates"[^>]*aria-labelledby="updatesTitle"/);
  assert.match(html, /id="previewLatestVersion">v1\.8\.0/);
  assert.match(html, /class="update-demo-tag">演示数据<\/span>/);
  assert.match(html, /data-action="check-plugin-updates"/);
  assert.match(html, /data-action="download-plugin-update"/);
  assert.match(html, /此预览仅展示更新入口与操作状态，不会发起真实下载/);
  assert.match(script, /updates:'版本更新'/);
  assert.match(script, /act==='open-updates'/);
  assert.match(script, /act==='check-plugin-updates'/);
  assert.match(script, /act==='download-plugin-update'/);
  assert.match(script, /function goBack\(\)/);
  assert.doesNotThrow(() => new Function(script));
});

test("v5 aligns AEP and managed-library motion with pairing interactions", () => {
  const html = fs.readFileSync(previewPath, "utf8");
  const script = html.match(/<script>([\s\S]*?)<\/script>/)?.[1] || "";

  assert.match(html, /--motion-press:120ms/);
  assert.match(html, /--motion-state:180ms/);
  assert.match(html, /--motion-panel:240ms/);
  assert.match(html, /--ease-out-ui:cubic-bezier\(\.23,1,\.32,1\)/);
  assert.match(html, /\.tree-row\.active,\.manage-card\.selected/);
  assert.match(html, /\.tree-row:hover,\.manage-card:hover,\.decision-card:hover/);
  assert.match(html, /\.content-swap\.is-ready/);
  assert.match(html, /\.modal-wrap\.is-open \.modal/);
  assert.match(html, /\.drawer\.is-open/);
  assert.match(html, /body\.reduce-motion \*/);
  assert.match(html, /body\.keyboard-nav \.content-swap/);
  assert.match(script, /function revealPanel\(root\)/);
  assert.match(script, /classList\.add\('keyboard-nav'\)/);
  assert.match(script, /classList\.remove\('keyboard-nav'\)/);
  assert.match(script, /behavior:prefersReducedMotion\(\)\|\|document\.body\.classList\.contains\('keyboard-nav'\)\?'auto':'smooth'/);
  assert.match(script, /function renderAepInspector\(c\)/);
  assert.match(script, /data-preview-time/);
  assert.match(script, /previewTime=c\.previewTime\|\|'2\.00'/);
  assert.match(script, /预览时间已更新/);
  assert.doesNotMatch(script, /button class="ghost-btn" data-action="aep-preview">查看大图<\/button>/);
  assert.match(html, /data-action="select-visible" aria-pressed="false">全选当前<\/button>/);
  assert.match(html, /\.tree-disclosure\{/);
  assert.match(html, /\.tree-head,\.tree-row\{grid-template-columns:14px 24px 26px.*column-gap:5px/);
  assert.match(html, /\.tree-node-children\{display:grid;gap:2px;margin-left:4px;padding-left:4px/);
  assert.match(html, /\.tree-node-children>\.tree-row\{grid-template-columns:6px 24px 26px/);
  assert.match(html, /\.tree-node-children>\.tree-row \.tree-disclosure-spacer\{width:6px\}/);
  assert.match(html, /\.tree-node-children\{/);
  assert.match(script, /let aepTreeExpanded=true/);
  assert.match(script, /function renderAepTree\(\)/);
  assert.match(script, /list\.setAttribute\('role','tree'\)/);
  assert.match(script, /data-tree-toggle/);
  assert.match(script, /const renderAepFlat=renderAep/);
  assert.match(script, /allVisibleSelected=visible\.length>0&&visible\.every\(c=>c\.selected\)/);
  assert.match(script, /已取消全选当前合成/);
  assert.match(script, /function renderManageInspector\(p\)/);
  assert.match(script, /function ensureManagedTypeDecision\(\)/);
  assert.match(script, /function replaceManagedTypeAction\(\)/);
  assert.match(script, /list\.querySelector\('\[data-action="add-type"\]'\)\?\.remove\(\)/);
  assert.match(script, /create\.querySelector\('strong'\)\.textContent='项目新增包装'/);
  assert.match(script, /heading\?\.remove\(\);note\?\.remove\(\)/);
  assert.match(script, /设计更新 · 新 ID 关联旧版 · 预计/);
  assert.match(script, /新包装从 v01 开始/);
  assert.match(script, /已准备发布新版本/);
  assert.match(script, /function prepareManagedAdd\(p,source\)/);
  assert.match(script, /async function managedPickerFilesFromDirectory\(directory,fs,path\)/);
  assert.match(script, /async function openManagedAddSelector\(\)/);
  assert.match(script, /function bindManagedAddButton\(card\)/);
  const managedAddSelector = script.slice(
    script.indexOf("async function openManagedAddSelector()"),
    script.indexOf("function clearManagedAddDraft()")
  );
  assert.match(managedAddSelector, /window\.eagle\?\.dialog/);
  assert.match(managedAddSelector, /showOpenDialog\(/);
  assert.match(managedAddSelector, /properties:\['openFile','openDirectory','multiSelections'\]/);
  assert.match(managedAddSelector, /routeHomeFiles\(files,source==='aep'\?'aep':source\)/);
  assert.doesNotMatch(managedAddSelector, /openModal\(/);
  assert.match(script, /导入 AEP 文件或整个文件夹/);
  assert.doesNotMatch(script, /data-managed-add-source=/);
  assert.doesNotMatch(script, /function bindProjectAddMenu\(card\)/);
  assert.doesNotMatch(script, /data-managed-add-choice/);
  assert.match(script, /function managedAddPairsFromFiles\(files\)/);
  assert.doesNotMatch(html, /\.managed-add-choices/);
  assert.doesNotMatch(html, /project-add-options/);
  assert.match(script, /aria-label','项目新增包装'/);
  assert.doesNotMatch(script, /aria-haspopup="dialog" aria-controls="modalContent"/);
  assert.match(script, /version:'v01'/);
  assert.match(script, /function openAddType\(\)/);
  assert.match(script, /function upgradeManagedTypeSplit\(p\)/);
  assert.match(script, /function bindManagedTypeSplit\(p\)/);
  assert.match(script, /managed-type-split/);
  assert.match(html, /#manageInspector \.managed-type-split:focus-within/);
  assert.match(html, /#manageInspector \.managed-type-split:has\(\.managed-type-toggle\[aria-expanded="true"\]\)/);
  assert.match(html, /#manageInspector \.managed-type-split \.managed-type-toggle\.package-type-trigger\[aria-expanded="true"\]\{background:transparent!important\}/);
  assert.match(html, /#manageInspector \.managed-type-split \.managed-type-toggle:active\{transform:none\}/);
  assert.match(script, /data-package-type-scope="managed"/);
  assert.match(script, /if\(act==='add-type'\)\{openAddType\(\)\}/);
  assert.match(script, /const addTypeOptionValue='__add_type__'/);
  assert.match(script, /＋ 新增包装类型/);
  assert.match(script, /function interceptAddTypeOption\(event\)/);
  assert.match(script, /function upgradePackageTypePickers\(\)/);
  assert.match(script, /function managedTypeMenuOptions\(selected='',id='managed-type'\)/);
  assert.match(html, /\.package-type-menu-tools\{position:sticky/);
  assert.match(html, /\.package-type-search\{/);
  assert.match(html, /\.package-type-add-button\{/);
  assert.match(script, /document\.addEventListener\('click',event=>\{if\(!event\.target\.closest\('\.package-type-picker,\.package-type-menu'\)\)closePackageTypePickers\(\)\}\)/);
  assert.match(script, /function addPackageTypeFromMenu\(menu,input,button\)/);
  assert.match(script, /placeholder='搜索包装类型'/);
  assert.match(script, /将搜索框中的文字新增为包装类型/);
  assert.match(script, /function enhancePackageTypeMenus\(\)/);
  assert.match(script, /const openPackageTypePickerWithSearch=openPackageTypePicker/);
  assert.match(script, /menu\.querySelectorAll\('\[data-package-type-value=""\]'\)\.forEach\(option=>option\.remove\(\)\)/);
  assert.match(html, /\.package-type-search:focus\{border-color:var\(--line-2\);box-shadow:none;outline:0\}/);
  assert.match(script, /pendingManagedType/);
  assert.doesNotMatch(script, /function openTypeMigration\(/);
  assert.match(script, /function openPackageTypePicker\(trigger\)/);
  assert.match(script, /setAttribute\('role','listbox'\)/);
  assert.match(html, /\.package-type-menu\{position:fixed/);
  assert.match(html, /\.candidate\{grid-template-columns:64px minmax\(0,1fr\) auto\}/);
  assert.match(html, /\.managed-file-read\{/);
  assert.match(script, /document\.body\.appendChild\(menu\)/);
  assert.match(script, /function formatManagedFileSize\(size\)/);
  assert.match(script, /data-managed-file-input/);
  assert.match(script, /data-read-managed-file/);
  assert.match(script, /外部读取 · 待确认/);
  assert.match(script, /menu\.style\.top=/);
  assert.match(html, /\.card-type-select\{appearance:none/);
  assert.match(script, /创建全局包装类型，并同步目录与 X\.bot 检索/);
  assert.match(html, /data-managed-asset="preview"/);
  assert.match(html, /data-managed-asset="source"/);
  assert.match(script, /\$\('#manageInspector \[data-action="repair-current"\]'\)\?\.remove\(\)/);
  assert.match(script, /替换单个 PNG 或 ZIP 时直接点击左侧卡片上的对应状态标签/);
  assert.match(script, /openManagedReplace\(p,button\.dataset\.managedAsset\)/);
  assert.match(script, /function refineManagedInspector\(p\)/);
  assert.match(script, /function expandManagedTechnical\(\)/);
  assert.match(script, /summary\.replaceWith\(heading\)/);
  assert.match(script, /inspector\.querySelector\('\.preview-actions'\)\?\.remove\(\)/);
  assert.match(script, /frame\.setAttribute\('role','button'\)/);
  assert.match(script, /\['new-package','new-version'\]/);
  assert.match(html, /\.decision-mark-type::before/);
  assert.match(html, /\.decision-mark-version::before/);
  assert.match(html, /\.decision-mark-package::before/);
  assert.match(script, /function bindPreviewViewer\(\)/);
  assert.match(script, /function bindPreviewViewerWithShrink\(\)/);
  assert.match(script, /Math\.abs\(art\.offsetWidth\*state\.zoom-viewer\.clientWidth\)/);
  assert.match(script, /clamp\(next,\.35,3\)/);
  assert.match(script, /tools\[0\]\.disabled=state\.zoom<=\.35/);
  assert.match(script, /function bindPreviewWheelFallback\(\)/);
  assert.match(script, /function bindPreviewInteractionDelegate\(\)/);
  assert.match(script, /document\.addEventListener\('wheel',handleWheel,\{capture:true,passive:false\}\)/);
  assert.match(script, /viewer\._xbotPreviewState/);
  assert.match(script, /addEventListener\('wheel',forwardWheel,\{capture:true,passive:false\}\)/);
  assert.match(script, /addEventListener\('mousewheel',forwardWheel/);
  assert.match(html, /\.modal\.preview-modal\{width:min\(1180px,calc\(100vw - 40px\)\)/);
  assert.match(html, /\.modal\.preview-modal \.modal-body\{display:flex;min-height:0;flex:1;flex-direction:column\}/);
  assert.match(html, /@media \(max-width:720px\).*\.modal\.preview-modal\{width:calc\(100vw - 24px\)/);
  assert.match(script, /\$\('#modalContent'\)\?\.classList\.remove\('preview-modal'\)/);
  assert.match(script, /const openModalBaseV5=openModal/);
  assert.match(script, /content\?\.classList\.toggle\('preview-modal',Boolean\(content\?\.querySelector\('\.viewer'\)\)\)/);
  assert.match(script, /addEventListener\('wheel'/);
  assert.match(script, /passive:false/);
  assert.match(script, /addEventListener\('pointerdown'/);
  assert.match(script, /addEventListener\('dblclick'/);
  assert.match(script, /tools\[1\]\.setAttribute\('aria-label','适应预览'\)/);
  assert.match(script, /#treeList \.tree-row/);
  assert.match(script, /#manageGrid \.manage-card/);
  assert.doesNotThrow(() => new Function(script));
});
